### PR TITLE
Update linting actions to support GH Actions summary

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Description of the Change
This PR updates our linting workflows to support new GH Actions summary feature:
- Change the eslint workflow to use `lint:js` script to generate the JSON report for `ataylorme/eslint-annotate-action` and https://github.com/10up/eslint-json-to-md.
- Use the `EXTRA_ARGS` flag introduced in https://github.com/10up/wpcs-action/pull/12 to generate a JSON report for https://github.com/10up/phpcs-json-to-md.

### Verification Process

The failed workflow: https://github.com/10up/maps-block-apple/actions/runs/2331451639

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Credits

Props @dinhtungdu

### CODE REVIEW

**Comment by dinhtungdu** [comment]
Leave this PR as a draft until https://github.com/10up/wpcs-action/pull/12 is merged.

**Comment by jeffpaul** [comment]
@dinhtungdu that WPCS item is merged, good to open this PR up for review now?

**Comment by dinhtungdu** [comment]
@jeffpaul I will mark this ready for review after releasing version 1.3.4 for WPCS because I want to keep using the `stable` branch.

**Comment by dinhtungdu** [comment]
@fabiankaegy This is ready for review. Can you please take a look?

**Comment by jeffpaul** [comment]
@fabiankaegy looking for your review/feedback here, please and thanks!

**Review by fabiankaegy — APPROVED** [review]
Love this :)

**Comment by jeffpaul** [comment]
@dinhtungdu probably worth documenting this in /actions-wordpress/, /wpcs-action/, and/or /open-source-best-practices/ so others can copy/paste and benefit from this great work!

**Comment by dinhtungdu** [comment]
> @dinhtungdu probably worth documenting this in /actions-wordpress/, /wpcs-action/, and/or /open-source-best-practices/ so others can copy/paste and benefit from this great work!

I create https://github.com/10up/actions-wordpress/pull/38 per your suggestion. Thank you so much!

**Pull request merged**
