### PR TITLE
Feature/add wp env for local development

### PR DESCRIPTION
**Pull request by fabiankaegy**
### Description of the Change
In order to make it easier to get up and running and to contribute to the project I have added the [`@wordpress/env`](https://npmjs.com/package/@wordpress/env) package with configuration to allow using `npm run wp-env start` to spin up a local WordPress environment to work on the plugin.

### CODE REVIEW

**Review by dinhtungdu — DISMISSED** [review]
Look good to me! 👍

**Comment by jeffpaul** [comment]
@fabiankaegy mind resolving the merge conflict so this can get merged in?

**Comment by jeffpaul** [comment]
@fabiankaegy may be worth a note in the README.md that this is available, then resolving merge conflicts, then can probably merge in.

**Comment by fabiankaegy** [comment]
@jeffpaul  I have rebased this PR and added some documentation to the `CONTRIBUTING.md` file

**Pull request merged**
