### PR TITLE
Minimum PHP version bumped to 7.4

### LINKED ISSUE #131: Bump WordPress and PHP minimums
Bump WP & PHP Minimums to the following
 
- [ ] WordPress to 5.7
- [ ] PHP to 7.4
- [ ] Remove any no-longer-needed conditional code for older version support.
- [ ] Take a look at adjusting our testing matrices, if applicable.
- [ ] Bump the minimums in plugin documentation and header fields.

### PR DESCRIPTION
**Pull request by jayedul**
### Description of the Change
Minimum WP and PHP version requirement bumped to 5.8 and 7.4 respectively. 

Closes #131 

### How to test the Change
There's not much change that needs test. Only the minimum WP and PHP version bumped.

### CODE REVIEW

**Comment by dkotter** [comment]
Code here looks good but a couple suggestions:

- Would be ideal to ensure our linting action is using PHP 7.4, so we can be sure we catch any code issues that may not work correctly on that version. I believe we can either change this in the `lint.yml` file or in our `.phpcs.xml` file
- In the `README.md` file, a couple references to WP and PHP versions need updated

**Comment by jeffpaul** [comment]
@jayedul are you able to help update to handle PHP 7.4 in the linting action?

**Comment by csloisel** [comment]
I have updated this PR to help resolve #131 

- Updated branch from develop since it was getting pretty stale
- Updated the minimum WP version from 5.7 to 5.8 since that was already partially done on develop
- Updated the composer config to get phpcs working
- Added a composer script for phpcs compat with version 7.4
- Added a github workflow job to run phpcs compat with version 7.4

It looks like there are some WPCS failures after this update, but i'm unsure if those should be addressed on this branch or not.

**Review by faisal-alvi — COMMENTED** [review]
@csloisel I appreciate your work on this. The WPCS failures don't appear to be relevant to the current PR. However, can you please resolve the conflicts?

**Review by faisal-alvi — DISMISSED** [review]
@jayedul thank you for your work. I've changed the title because WP min support was already bumped to `5.8`. (https://github.com/10up/maps-block-apple/commit/f708c3584adf9f03d1966aa4dc8cd74ce454731c)

**Comment by jeffpaul** [comment]
@jayedul looks like there's an e2e failure on WP trunk (e.g., the 6.2 version)... can you check and see if that's coming from this change (and thus something we should resolve here) or coming from elsewhere (and thus something we can ignore and merge this PR)?

**Comment by jayedul** [comment]
@jeffpaul it seems nothing to do in this repository. Rather here we'll have to modify the line to target only the first selected element to type in. [https://github.com/10up/cypress-wp-utils/blob/trunk/src/commands/create-post.ts#L88](https://github.com/10up/cypress-wp-utils/blob/trunk/src/commands/create-post.ts#L88)

**Comment by jayedul** [comment]
I changed in my local system on WP master branch, and it worked this way. 
Screenshot 2023-02-24 at 3 33 15 PM

**Review by faisal-alvi — APPROVED** [review]
Great job on this, @jayedul! Looks good to me. Regarding the WPCS failure, as it's not related to the current PR, it can be ignored. If you think the solution you used in your local should be added, would you mind creating a separate PR for that? Thanks again for your contribution!

**Comment by jayedul** [comment]
@faisal-alvi 
Just for reference. I found @cadic has opened a pull request that resolves the cypress issue too along with some other bugs. 
https://github.com/10up/cypress-wp-utils/pull/89

**Pull request merged**
