### PR TITLE
Add support for the WordPress.org plugin preview

### PR DESCRIPTION
**Pull request by dkotter**
### Description of the Change

WordPress.org recently launched support for plugin previews utilizing the WordPress Playground feature. Plugins wanting to take advantage of this need to opt in by setting up a `blueprint.json` file that configures how the preview should load. This PR adds in that file that does the following:

1. Sets up an environment running PHP 7.4 (our supported minimum) and the latest version of WordPress
2. Logs into the admin
3. Installs and activates the plugin
4. Sends the user to a post that has the Apple Maps block in place

Note that this PR is targeted to `trunk` so we can take advantage of our Plugin Asset Update Action to deploy these changes without having to push out a new release.

Also note once these changes are on .org, the preview button will need to be enabled in a test state. Once verified as working, we can enable it for all users.

### How to test the Change

The WordPress Playground allows you to spin up a new environment directly through the URL, by going to `https://playground.wordpress.net/#` and pasting your JSON config after the `#`. In this case, the URL should be: https://playground.wordpress.net/#{%20%22$schema%22:%20%22https://playground.wordpress.net/blueprint-schema.json%22,%20%22landingPage%22:%20%22\/wp-admin\/post.php?post=6&action=edit%22,%20%22preferredVersions%22:%20{%20%22php%22:%20%227.4%22,%20%22wp%22:%20%22latest%22%20},%20%22phpExtensionBundles%22:%20[%22kitchen-sink%22],%20%22steps%22:%20[%20{%20%22step%22:%20%22login%22,%20%22username%22:%20%22admin%22,%20%22password%22:%20%22password%22%20},%20{%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20{%20%22resource%22:%20%22wordpress.org\/plugins%22,%20%22slug%22:%20%22maps-block-apple%22%20},%20%22options%22:%20{%20%22activate%22:%20true%20}%20},%20{%20%22step%22:%20%22importFile%22,%20%22file%22:%20{%20%22resource%22:%20%22url%22,%20%22url%22:%20%22https:\/\/raw.githubusercontent.com\/10up\/maps-block-apple\/385fb9705624c2fe6822ac399ed08f09a5e80388\/.wordpress-org/blueprints\/demo-data.xml%22%20}%20}%20]%20}

### Changelog Entry

> Added - Support for the WordPress.org plugin preview

### Credits

Props @dkotter

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by jeffpaul** [comment]
@dkotter worth asking if you think it might be better to drop them into the editor with an empty Apple Maps block that they'll need to configure to test/demo?

**Comment by dkotter** [comment]
> @dkotter worth asking if you think it might be better to drop them into the editor with an empty Apple Maps block that they'll need to configure to test/demo?

Makes sense (though in testing, seems we have an over aggressive check for the credentials. I get the message `Missing Private Key` over and over as I try and edit a post with that block). The new test URL is https://playground.wordpress.net/#{%20%22$schema%22:%20%22https://playground.wordpress.net/blueprint-schema.json%22,%20%22landingPage%22:%20%22\/wp-admin\/post.php?post=6&action=edit%22,%20%22preferredVersions%22:%20{%20%22php%22:%20%227.4%22,%20%22wp%22:%20%22latest%22%20},%20%22phpExtensionBundles%22:%20[%22kitchen-sink%22],%20%22steps%22:%20[%20{%20%22step%22:%20%22login%22,%20%22username%22:%20%22admin%22,%20%22password%22:%20%22password%22%20},%20{%20%22step%22:%20%22installPlugin%22,%20%22pluginZipFile%22:%20{%20%22resource%22:%20%22wordpress.org\/plugins%22,%20%22slug%22:%20%22maps-block-apple%22%20},%20%22options%22:%20{%20%22activate%22:%20true%20}%20},%20{%20%22step%22:%20%22importFile%22,%20%22file%22:%20{%20%22resource%22:%20%22url%22,%20%22url%22:%20%22https:\/\/raw.githubusercontent.com\/10up\/maps-block-apple\/385fb9705624c2fe6822ac399ed08f09a5e80388\/.wordpress-org/blueprints\/demo-data.xml%22%20}%20}%20]%20}

**Comment by jeffpaul** [comment]
@dkotter I see your comment on the `Missing Private Key` notifications... maybe we delay on checking there until someone clicks the `Confirm MapKit Credentials` button?

**Comment by dkotter** [comment]
> @dkotter I see your comment on the `Missing Private Key` notifications... maybe we delay on checking there until someone clicks the `Confirm MapKit Credentials` button?

Yeah, seems we can handle this check a bit better, though that's not related specifically to this PR. I'd suggest we open a new issue to track that and can proceed here, assuming no other changes are needed

**Review by jeffpaul — APPROVED** [review]
Looks good, thanks for getting this set up!

**Comment by jeffpaul** [comment]
Looks good now: https://wordpress.org/plugins/maps-block-apple/

**Pull request merged**
