### PR TITLE
Try: remove setting pages

### LINKED ISSUE #64: Block Directory: handling settings config
**Is your enhancement related to a problem? Please describe.**
Inheriting from #62 and from discussion with @fabiankaegy today, we're expecting that the Plugin Review Team will not approve our Settings page and related PHP code.  This issue covers the removal of that PHP code as well as how best to ensure that settings are exposed within Gutenberg for our Apple Maps block users.

**Describe the solution you'd like**

- [ ] remove PHP code related to Settings page
- [ ] discussion, decision, and implementation on how best to expose settings in Gutenberg (using 1-n of items below and/or other options not yet identified)
   - [ ] keep initial block state for settings config (seems best to keep this as initial set up/config state)
   - [ ] add block settings panel for settings config (this option requires a user to find an existing post/page with a maps block or create a test one to access the settings config)
   - [ ] add SlotFill with plugin icon disabled in top right of Gutenberg to expose menu item for block settings config (this option allows for always available option wherever a user happens to be within the Gutenberg editing experience)

**Designs**

TBD depending on decision for how best to present block settings config.

**Describe alternatives you've considered**

Keep as-is, but will likely mean the block will not be approved to appear in the Block Directory.

**Additional context**

It may be worth mocking up the various options and running some light user testing to gather data to help inform our decision.  It may also be worth crafting a blog post once we resolve this PR to share our learnings with others outlining options we considered and why we went the way we did.  @fabiankaegy is also going to open a Gutenberg issue to start conversation with that team on potentially adding a standard place for block plugins to all integrate their settings config instead of having plugins all use different UI locations for settings config.

### PR DESCRIPTION
**Pull request by dinhtungdu**
### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

Fixes #64

### CODE REVIEW

**Comment by fabiankaegy** [comment]
@dinhtungdu I'm not sure wether this is helpful but this was the point in time where the settings page got added. And I think you are basically trying to go back to that point. https://github.com/10up/maps-block-apple/commit/7314ceadca67db7c50ae968570c1c963e39b2778

**Comment by dinhtungdu** [comment]
@fabiankaegy I see. The reason I keep the setting part is using setting APIs is cleaner and shorter than our custom REST endpoints, see https://github.com/10up/maps-block-apple/blob/develop/src/components/EditAuthForm.js#L31-L38

**Comment by fabiankaegy** [comment]
@dinhtungdu 100% agree  👍 Just wanted to make sure you were aware that there was a point in time where the settings were already available in the Gutenberg IncpectorControls area :)

**Comment by dinhtungdu** [comment]
@fabiankaegy Thanks for the heads up! I saw the Auth setting panel code and added it back as well. We still need a place to update the credentials if the setting page is removed.

**Comment by jeffpaul** [comment]
Closing as apparently not a concern.

**Pull request closed without merging**
